CREATE DATABASE dbtde;

USE dbtde;

CREATE TABLE usuarios (
  id INT AUTO_INCREMENT, 
	nome VARCHAR(255) NOT NULL,
	sobrenome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	celular VARCHAR(255) NOT NULL,
	senha VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);